#!/bin/sh -e

### Local puppet run with puppet apply
/usr/bin/puppet apply /etc/puppetlabs/code/environments/production/manifests/site.pp

### Log puppet run status
if [ $? -eq 0 ]
then
 /usr/bin/logger -i "Puppet has run successfully" -t "puppet-run"
 exit 0
else
 /usr/bin/logger -i "Puppet has ran into an error, please run Puppet manually" -t "puppet-run"
 exit 1
fi
